[package]
name = "grids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatvec = "0.3.0"
ndarray = "0.15.6"
smallvec = "1.10.0"
